import { ProductItemProps } from "@/app/types/general";

export const salonProducts: ProductItemProps[] = [
  {
    _id: "ayam",
    image: "/si.jpeg",
    productName: "Luxury Hair Treatment",
    rating: 4.5,
    estimation: 60,
    price: 250000,
  },
  {
    _id: "aya",
    image: "/si.jpeg",
    productName: "Premium Haircut",
    rating: 4.8,
    estimation: 45,
    price: 275000,
  },
  {
    _id: "ay",
    image: "/si.jpeg",
    productName: "Deep Conditioning",
    rating: 4.2,
    estimation: 30,
    price: 310900,
  },
  {
    _id: "a",
    image: "/si.jpeg",
    productName: "Blowout Styling",
    rating: 4.7,
    estimation: 35,
    price: 125500,
  },
  {
    _id: "kuday",
    image: "/si.jpeg",
    productName: "Hair Coloring",
    rating: 4.3,
    estimation: 90,
    price: 75100,
  },
  {
    _id: "kuda",
    image: "/si.jpeg",
    productName: "Keratin Treatment",
    rating: 4.9,
    estimation: 120,
    price: 20000,
  },
  {
    _id: "kudaya",
    image: "/si.jpeg",
    productName: "Beard Trim",
    rating: 4.1,
    estimation: 20,
    price: 1000000,
  },
  {
    _id: "kua",
    image: "/si.jpeg",
    productName: "Scalp Massage",
    rating: 4.6,
    estimation: 25,
    price: 321231,
  },
  {
    _id: "facial1",
    image: "/si.jpeg",
    productName: "Signature Facial Treatment",
    rating: 4.7,
    estimation: 60,
    price: 350000,
  },
  {
    _id: "wax1",
    image: "/si.jpeg",
    productName: "Full Body Waxing",
    rating: 4.3,
    estimation: 90,
    price: 450000,
  },
  {
    _id: "nail1",
    image: "/si.jpeg",
    productName: "Deluxe Manicure & Pedicure",
    rating: 4.8,
    estimation: 75,
    price: 280000,
  },
  {
    _id: "mass1",
    image: "/si.jpeg",
    productName: "Aromatherapy Massage",
    rating: 4.9,
    estimation: 60,
    price: 400000,
  },
  {
    _id: "lash1",
    image: "/si.jpeg",
    productName: "Eyelash Extensions",
    rating: 4.5,
    estimation: 90,
    price: 375000,
  },
  {
    _id: "brow1",
    image: "/si.jpeg",
    productName: "Microblading Session",
    rating: 4.6,
    estimation: 120,
    price: 1200000,
  },
  {
    _id: "tan1",
    image: "/si.jpeg",
    productName: "Spray Tan Application",
    rating: 4.2,
    estimation: 30,
    price: 250000,
  },
  {
    _id: "make1",
    image: "/si.jpeg",
    productName: "Bridal Makeup Package",
    rating: 4.9,
    estimation: 90,
    price: 850000,
  },
  {
    _id: "skin1",
    image: "/si.jpeg",
    productName: "Chemical Peel Treatment",
    rating: 4.4,
    estimation: 45,
    price: 500000,
  },
  {
    _id: "body1",
    image: "/si.jpeg",
    productName: "Body Scrub & Wrap",
    rating: 4.7,
    estimation: 75,
    price: 420000,
  },
  {
    _id: "hair2",
    image: "/si.jpeg",
    productName: "Balayage Coloring",
    rating: 4.8,
    estimation: 180,
    price: 1500000,
  },
  {
    _id: "face2",
    image: "/si.jpeg",
    productName: "Microdermabrasion",
    rating: 4.5,
    estimation: 50,
    price: 380000,
  },
  {
    _id: "nail2",
    image: "/si.jpeg",
    productName: "Gel Polish Application",
    rating: 4.6,
    estimation: 45,
    price: 175000,
  },
  {
    _id: "mass2",
    image: "/si.jpeg",
    productName: "Hot Stone Massage",
    rating: 4.9,
    estimation: 80,
    price: 550000,
  },
  {
    _id: "lash2",
    image: "/si.jpeg",
    productName: "Lash Lift & Tint",
    rating: 4.7,
    estimation: 60,
    price: 320000,
  },
  {
    _id: "brow2",
    image: "/si.jpeg",
    productName: "Brow Lamination",
    rating: 4.5,
    estimation: 45,
    price: 280000,
  },
  {
    _id: "make2",
    image: "/si.jpeg",
    productName: "Evening Glam Makeup",
    rating: 4.8,
    estimation: 60,
    price: 450000,
  },
  {
    _id: "skin2",
    image: "/si.jpeg",
    productName: "LED Light Therapy",
    rating: 4.3,
    estimation: 30,
    price: 300000,
  },
  {
    _id: "body2",
    image: "/si.jpeg",
    productName: "Cellulite Reduction",
    rating: 4.2,
    estimation: 60,
    price: 480000,
  },
  {
    _id: "hair3",
    image: "/si.jpeg",
    productName: "Brazilian Blowout",
    rating: 4.7,
    estimation: 150,
    price: 1250000,
  },
];
