import { ProductItemProps } from "@/app/types/general";

export const salonProducts: ProductItemProps[] = [
  {
    _id: "ayam",
    assetRef: "/si.svg",
    name: "Luxury Hair Treatment",
    ratingAverage: 4.5,
    estimation: 60,
    price: 250000,
  },
  {
    _id: "aya",
    assetRef: "/si.svg",
    name: "Premium Haircut",
    ratingAverage: 4.8,
    estimation: 45,
    price: 275000,
  },
  {
    _id: "ay",
    assetRef: "/si.svg",
    name: "Deep Conditioning",
    ratingAverage: 4.2,
    estimation: 30,
    price: 310900,
  },
  {
    _id: "a",
    assetRef: "/si.svg",
    name: "Blowout Styling",
    ratingAverage: 4.7,
    estimation: 35,
    price: 125500,
  },
  {
    _id: "kuday",
    assetRef: "/si.svg",
    name: "Hair Coloring",
    ratingAverage: 4.3,
    estimation: 90,
    price: 75100,
  },
  {
    _id: "kuda",
    assetRef: "/si.svg",
    name: "Keratin Treatment",
    ratingAverage: 4.9,
    estimation: 120,
    price: 20000,
  },
  {
    _id: "kudaya",
    assetRef: "/si.svg",
    name: "Beard Trim",
    ratingAverage: 4.1,
    estimation: 20,
    price: 1000000,
  },
  {
    _id: "kua",
    assetRef: "/si.svg",
    name: "Scalp Massage",
    ratingAverage: 4.6,
    estimation: 25,
    price: 321231,
  },
  {
    _id: "facial1",
    assetRef: "/si.svg",
    name: "Signature Facial Treatment",
    ratingAverage: 4.7,
    estimation: 60,
    price: 350000,
  },
  {
    _id: "wax1",
    assetRef: "/si.svg",
    name: "Full Body Waxing",
    ratingAverage: 4.3,
    estimation: 90,
    price: 450000,
  },
  {
    _id: "nail1",
    assetRef: "/si.svg",
    name: "Deluxe Manicure & Pedicure",
    ratingAverage: 4.8,
    estimation: 75,
    price: 280000,
  },
  {
    _id: "mass1",
    assetRef: "/si.svg",
    name: "Aromatherapy Massage",
    ratingAverage: 4.9,
    estimation: 60,
    price: 400000,
  },
  {
    _id: "lash1",
    assetRef: "/si.svg",
    name: "Eyelash Extensions",
    ratingAverage: 4.5,
    estimation: 90,
    price: 375000,
  },
  {
    _id: "brow1",
    assetRef: "/si.svg",
    name: "Microblading Session",
    ratingAverage: 4.6,
    estimation: 120,
    price: 1200000,
  },
  {
    _id: "tan1",
    assetRef: "/si.svg",
    name: "Spray Tan Application",
    ratingAverage: 4.2,
    estimation: 30,
    price: 250000,
  },
  {
    _id: "make1",
    assetRef: "/si.svg",
    name: "Bridal Makeup Package",
    ratingAverage: 4.9,
    estimation: 90,
    price: 850000,
  },
  {
    _id: "skin1",
    assetRef: "/si.svg",
    name: "Chemical Peel Treatment",
    ratingAverage: 4.4,
    estimation: 45,
    price: 500000,
  },
  {
    _id: "body1",
    assetRef: "/si.svg",
    name: "Body Scrub & Wrap",
    ratingAverage: 4.7,
    estimation: 75,
    price: 420000,
  },
  {
    _id: "hair2",
    assetRef: "/si.svg",
    name: "Balayage Coloring",
    ratingAverage: 4.8,
    estimation: 180,
    price: 1500000,
  },
  {
    _id: "face2",
    assetRef: "/si.svg",
    name: "Microdermabrasion",
    ratingAverage: 4.5,
    estimation: 50,
    price: 380000,
  },
  {
    _id: "nail2",
    assetRef: "/si.svg",
    name: "Gel Polish Application",
    ratingAverage: 4.6,
    estimation: 45,
    price: 175000,
  },
  {
    _id: "mass2",
    assetRef: "/si.svg",
    name: "Hot Stone Massage",
    ratingAverage: 4.9,
    estimation: 80,
    price: 550000,
  },
  {
    _id: "lash2",
    assetRef: "/si.svg",
    name: "Lash Lift & Tint",
    ratingAverage: 4.7,
    estimation: 60,
    price: 320000,
  },
  {
    _id: "brow2",
    assetRef: "/si.svg",
    name: "Brow Lamination",
    ratingAverage: 4.5,
    estimation: 45,
    price: 280000,
  },
  {
    _id: "make2",
    assetRef: "/si.svg",
    name: "Evening Glam Makeup",
    ratingAverage: 4.8,
    estimation: 60,
    price: 450000,
  },
  {
    _id: "skin2",
    assetRef: "/si.svg",
    name: "LED Light Therapy",
    ratingAverage: 4.3,
    estimation: 30,
    price: 300000,
  },
  {
    _id: "body2",
    assetRef: "/si.svg",
    name: "Cellulite Reduction",
    ratingAverage: 4.2,
    estimation: 60,
    price: 480000,
  },
  {
    _id: "hair3",
    assetRef: "/si.svg",
    name: "Brazilian Blowout",
    ratingAverage: 4.7,
    estimation: 150,
    price: 1250000,
  },
];

export const dummyReviews = [
  {
    _id: "1",
    review: "Great service!",
    rating: 5,
    product: {
      _id: "1",
      name: "Product A",
      ratingAverage: 4.5,
    },
    user: {
      _id: "1",
      name: "User A",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "2",
    review: `lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.`,
    rating: 3,
    product: {
      _id: "2",
      name: "Product B",
      ratingAverage: 3.5,
    },
    user: {
      _id: "2",
      name: "User B",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "3",
    review:
      "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    rating: 5,
    product: {
      _id: "3",
      name: "Product C",
      ratingAverage: 4.8,
    },
    user: {
      _id: "3",
      name: "User C",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "4",
    review: "Could be better.",
    rating: 2,
    product: {
      _id: "4",
      name: "Product D",
      ratingAverage: 2.9,
    },
    user: {
      _id: "4",
      name: "User D",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "5",
    review: "Loved it!",
    rating: 5,
    product: {
      _id: "5",
      name: "Product E",
      ratingAverage: 4.9,
    },
    user: {
      _id: "5",
      name: "User E",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "6",
    review: "Very satisfied.",
    rating: 4,
    product: {
      _id: "6",
      name: "Product F",
      ratingAverage: 4.2,
    },
    user: {
      _id: "6",
      name: "User F",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "7",
    review: "Not what I expected.",
    rating: 2,
    product: {
      _id: "7",
      name: "Product G",
      ratingAverage: 2.5,
    },
    user: {
      _id: "7",
      name: "User G",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "8",
    review: "Amazing quality!",
    rating: 5,
    product: {
      _id: "8",
      name: "Product H",
      ratingAverage: 4.7,
    },
    user: {
      _id: "8",
      name: "User H",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "9",
    review: "Just okay.",
    rating: 3,
    product: {
      _id: "9",
      name: "Product I",
      ratingAverage: 3.0,
    },
    user: {
      _id: "9",
      name: "User I",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "10",
    review: "Would recommend.",
    rating: 4,
    product: {
      _id: "10",
      name: "Product J",
      ratingAverage: 4.3,
    },
    user: {
      _id: "10",
      name: "User J",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "11",
    review: "Very helpful staff.",
    rating: 5,
    product: {
      _id: "11",
      name: "Product K",
      ratingAverage: 4.6,
    },
    user: {
      _id: "11",
      name: "User K",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "12",
    review: "Not worth the price.",
    rating: 2,
    product: {
      _id: "12",
      name: "Product L",
      ratingAverage: 2.8,
    },
    user: {
      _id: "12",
      name: "User L",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "13",
    review: "Fast delivery.",
    rating: 4,
    product: {
      _id: "13",
      name: "Product M",
      ratingAverage: 4.1,
    },
    user: {
      _id: "13",
      name: "User M",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "14",
    review: "Very comfortable.",
    rating: 5,
    product: {
      _id: "14",
      name: "Product N",
      ratingAverage: 4.8,
    },
    user: {
      _id: "14",
      name: "User N",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "15",
    review: "Average experience.",
    rating: 3,
    product: {
      _id: "15",
      name: "Product O",
      ratingAverage: 3.2,
    },
    user: {
      _id: "15",
      name: "User O",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "16",
    review: "Superb!",
    rating: 5,
    product: {
      _id: "16",
      name: "Product P",
      ratingAverage: 4.9,
    },
    user: {
      _id: "16",
      name: "User P",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "17",
    review: "Not satisfied.",
    rating: 1,
    product: {
      _id: "17",
      name: "Product Q",
      ratingAverage: 1.9,
    },
    user: {
      _id: "17",
      name: "User Q",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "18",
    review: "Good value.",
    rating: 4,
    product: {
      _id: "18",
      name: "Product R",
      ratingAverage: 4.0,
    },
    user: {
      _id: "18",
      name: "User R",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "19",
    review: "Exceeded expectations.",
    rating: 5,
    product: {
      _id: "19",
      name: "Product S",
      ratingAverage: 4.7,
    },
    user: {
      _id: "19",
      name: "User S",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "20",
    review: "Disappointing.",
    rating: 2,
    product: {
      _id: "20",
      name: "Product T",
      ratingAverage: 2.3,
    },
    user: {
      _id: "20",
      name: "User T",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "21",
    review: "Very friendly staff.",
    rating: 5,
    product: {
      _id: "21",
      name: "Product U",
      ratingAverage: 4.6,
    },
    user: {
      _id: "21",
      name: "User U",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "22",
    review: "Product arrived damaged.",
    rating: 1,
    product: {
      _id: "22",
      name: "Product V",
      ratingAverage: 1.5,
    },
    user: {
      _id: "22",
      name: "User V",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "23",
    review: "Very clean and tidy.",
    rating: 5,
    product: {
      _id: "23",
      name: "Product W",
      ratingAverage: 4.8,
    },
    user: {
      _id: "23",
      name: "User W",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "24",
    review: "Would buy again.",
    rating: 4,
    product: {
      _id: "24",
      name: "Product X",
      ratingAverage: 4.4,
    },
    user: {
      _id: "24",
      name: "User X",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "25",
    review: "Too expensive.",
    rating: 2,
    product: {
      _id: "25",
      name: "Product Y",
      ratingAverage: 2.7,
    },
    user: {
      _id: "25",
      name: "User Y",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "26",
    review: "Perfect for my needs.",
    rating: 5,
    product: {
      _id: "26",
      name: "Product Z",
      ratingAverage: 4.9,
    },
    user: {
      _id: "26",
      name: "User Z",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "27",
    review: "Not as described.",
    rating: 2,
    product: {
      _id: "27",
      name: "Product AA",
      ratingAverage: 2.2,
    },
    user: {
      _id: "27",
      name: "User AA",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "28",
    review: "Very stylish.",
    rating: 4,
    product: {
      _id: "28",
      name: "Product AB",
      ratingAverage: 4.3,
    },
    user: {
      _id: "28",
      name: "User AB",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "29",
    review: "Quick response.",
    rating: 4,
    product: {
      _id: "29",
      name: "Product AC",
      ratingAverage: 4.2,
    },
    user: {
      _id: "29",
      name: "User AC",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "30",
    review: "Very poor quality.",
    rating: 1,
    product: {
      _id: "30",
      name: "Product AD",
      ratingAverage: 1.3,
    },
    user: {
      _id: "30",
      name: "User AD",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "31",
    review: "Fantastic!",
    rating: 5,
    product: {
      _id: "31",
      name: "Product AE",
      ratingAverage: 4.9,
    },
    user: {
      _id: "31",
      name: "User AE",
      assetRef: "/si.svg",
    },
  },
  {
    _id: "32",
    review: "Good but not great.",
    rating: 3,
    product: {
      _id: "32",
      name: "Product AF",
      ratingAverage: 3.6,
    },
    user: {
      _id: "32",
      name: "User AF",
      assetRef: "/si.svg",
    },
  },
];
