export const REGISTER_ENDPOINT = process.env.NEXT_PUBLIC_REGISTER_ENDPOINT;
export const EMAIL_VERIFICATION_ENDPOINT = process.env.NEXT_PUBLIC_EMAIL_VERIFICATION_ENDPOINT;
export const LOGIN_ENDPOINT = process.env.NEXT_PUBLIC_LOGIN_ENDPOINT;
export const RESET_PASSWORD_ENDPOINT = process.env.NEXT_PUBLIC_RESET_PASSWORD_ENDPOINT;
export const FORGOT_PASSWORD_ENDPOINT = process.env.NEXT_PUBLIC_FORGOT_PASSWORD_ENDPOINT;
export const VERIFY_TOKEN_RESET_PASSWORD_ENDPOINT = process.env.NEXT_PUBLIC_VERIFY_TOKEN_RESET_PASSWORD_ENDPOINT;

export const GET_USER_BY_ID_ENDPOINT = process.env.NEXT_PUBLIC_GET_USER_BY_ID_ENDPOINT;

export const GET_REVIEWS_ENDPOINT = process.env.NEXT_PUBLIC_GET_REVIEWS;

export const GET_CATEGORIES_ENDPOINT = process.env.NEXT_PUBLIC_GET_CATEGORIES;
export const GET_PRODUCTS_ENDPOINT = process.env.NEXT_PUBLIC_GET_PRODUCTS;

export const GET_CARTS_ENDPOINT = process.env.NEXT_PUBLIC_GET_CARTS;

export const GET_SCHEDULES = process.env.NEXT_PUBLIC_GET_SCHEDULES;
