export const REGISTER_ENDPOINT = process.env.NEXT_PUBLIC_REGISTER_ENDPOINT;
export const EMAIL_VERIFICATION_ENDPOINT = process.env.NEXT_PUBLIC_EMAIL_VERIFICATION_ENDPOINT;
export const LOGIN_ENDPOINT = process.env.NEXT_PUBLIC_LOGIN_ENDPOINT;
export const RESET_PASSWORD_ENDPOINT = process.env.NEXT_PUBLIC_RESET_PASSWORD_ENDPOINT;
export const FORGOT_PASSWORD_ENDPOINT = process.env.NEXT_PUBLIC_FORGOT_PASSWORD_ENDPOINT;
export const VERIFY_TOKEN_RESET_PASSWORD_ENDPOINT = process.env.NEXT_PUBLIC_VERIFY_TOKEN_RESET_PASSWORD_ENDPOINT;
