export enum TransactionStatus {
  PAID = "PAID",
  UNPAID = "UNPAID",
  EXPIRED = "EXPIRED",
  IN_PROGRESS = "IN_PROGRESS",
  CANCELED = "CANCELED",
  COMPLETED = "COMPLETED",
  PENDING = "PENDING",
  SCHEDULED = "SCHEDULED",
  CART = "CART",
}
